GRE_VOCABULARY_A_WORDS = {
    "Abate": "To reduce in amount, degree, or severity.",
    "Aberrant": "Deviating from the norm.",
    "Abjure": "To reject, abandon formally.",
    "Abstain": "To choose not to do something.",
    "Abysmal": "Very bad.",
    "Accolade": "An expression of praise.",
    "Acerbic": "Sour or bitter in taste or manner.",
    "Acquiesce": "To agree without protesting.",
    "Acrimony": "Bitterness and ill will.",
    "Adamant": "Unwilling to change one's mind.",
    "Adept": "Very skilled.",
    "Admonish": "To caution or criticize gently.",
    "Adroit": "Skillful, dexterous.",
    "Adulation": "Excessive praise.",
    "Adumbrate": "To sketch or outline.",
    "Adverse": "Unfavorable, unlucky, harmful.",
    "Advocate": "To speak in favor of.",
    "Aesthetic": "Concerning the appreciation of beauty.",
    "Affable": "Easy to talk to.",
    "Affinity": "A spontaneous feeling of closeness.",
    "Alacrity": "Brisk and cheerful readiness.",
    "Alleviate": "To make suffering, deficiency, or a problem less severe.",
    "Amalgamate": "To combine or unite to form one organization or structure.",
    "Ambiguous": "Open to more than one interpretation; having a double meaning.",
    "Ambivalent": "Having mixed feelings or contradictory ideas about something or someone.",
    "Ameliorate": "To make (something bad or unsatisfactory) better.",
    "Amenable": "(Of a person) easily persuaded or controlled.",
    "Anachronism": "A thing belonging or appropriate to a period other than that in which it exists, especially a thing that is conspicuously old-fashioned.",
    "Analogous": "Comparable in certain respects, typically in a way which makes clearer the nature of the things compared.",
    "Anoint": "To smear or rub with oil, typically as part of a religious ceremony.",
    "Anomaly": "Something that deviates from what is standard, normal, or expected.",
    "Antipathy": "A deep-seated feeling of dislike; aversion.",
    "Apathy": "Lack of interest, enthusiasm, or concern.",
    "Apocryphal": "(Of a story or statement) of doubtful authenticity, although widely circulated as being true.",
    "Apostate": "A person who renounces a religious or political belief or principle.",
    "Apprise": "To inform or tell (someone).",
    "Approbation": "Approval or praise.",
    "Arbitrary": "Based on random choice or personal whim, rather than any reason or system.",
    "Arcane": "Understood by few; mysterious or secret.",
    "Arduous": "Involving or requiring strenuous effort; difficult and tiring.",
    "Ascetic": "Characterized by severe self-discipline and abstention from indulgence.",
    "Assuage": "To make (an unpleasant feeling) less intense.",
    "Attenuate": "To reduce the force, effect, or value of.",
    "Audacious": "Willing to take bold risks.",
    "Austere": "Severe or strict in manner, attitude, or appearance.",
    "Avarice": "Extreme greed for wealth or material gain.",
        "Banal": "So lacking in originality as to be obvious and boring.",
    "Belie": "To give a false impression of; to contradict.",
    "Belligerent": "Hostile and aggressive.",
    "Benign": "Kind and gentle; not harmful.",
    "Beleaguer": "To trouble or harass; to besiege.",
    "Berate": "To scold or criticize angrily.",
    "Bilious": "Bad-tempered or irritable.",
    "Blithe": "Showing a casual and cheerful indifference considered to be improper.",
    "Bolster": "To support or strengthen.",
    "Bombastic": "High-sounding but with little meaning; inflated.",
    "Boorish": "Rude, insensitive, or ill-mannered.",
    "Bourgeois": "Characteristic of the middle class, typically with reference to its materialistic values.",
    "Brevity": "Concise and exact use of words in writing or speech.",
    "Bucolic": "Relating to the pleasant aspects of the countryside and country life.",
    "Burgeon": "To grow or increase rapidly; to flourish.",
    "Burnish": "To polish by rubbing; to make shiny.",
    "Buttress": "To support, strengthen, or reinforce.",
    "Brazen": "Bold and without shame.",
    "Broach": "To bring up or introduce a sensitive topic for discussion.",
    "Brusque": "Abrupt or offhand in speech or manner.",
    "Buoyant": "Cheerful and optimistic.",
    "Byzantine": "Complex and intricate; involving a great deal of administrative detail."
    "Cacophony": "A harsh, discordant mixture of sounds.",
    "Calumny": "A false and malicious statement designed to injure a reputation.",
    "Candor": "The quality of being open and honest in expression.",
    "Capricious": "Given to sudden and unaccountable changes of mood or behavior.",
    "Castigate": "To reprimand someone severely.",
    "Caustic": "Able to burn or corrode; sarcastic in a scathing way.",
    "Censure": "Express severe disapproval of someone or something.",
    "Chicanery": "The use of trickery to achieve a political, financial, or legal purpose.",
    "Cogent": "Clear, logical, and convincing.",
    "Commensurate": "Corresponding in size or degree; in proportion.",
    "Concur": "To agree or have the same opinion.",
    "Condone": "To accept or allow behavior that is morally wrong or offensive.",
    "Conflagration": "A large, destructive fire.",
    "Confound": "To cause surprise or confusion; to mix up.",
    "Connoisseur": "An expert judge in matters of taste.",
    "Consensus": "General agreement.",
    "Contrite": "Feeling or expressing remorse or penitence.",
    "Conundrum": "A confusing and difficult problem or question.",
    "Convoluted": "Extremely complex and difficult to follow.",
    "Copious": "Abundant in supply or quantity.",
    "Corroborate": "To confirm or give support to a statement, theory, or finding.",
    "Credulous": "Having or showing too great a readiness to believe things.",
    "Crescendo": "A gradual increase in loudness or intensity.",
    "Criterion": "A principle or standard by which something may be judged.",
    "Cryptic": "Having a meaning that is mysterious or obscure.",
        "Debacle": "A sudden and ignominious failure; a fiasco.",
    "Debilitate": "To weaken or enfeeble.",
    "Debunk": "To expose the falseness or hollowness of a myth, idea, or belief.",
    "Decorum": "Behavior in keeping with good taste and propriety.",
    "Deference": "Humble submission and respect.",
    "Defunct": "No longer existing or functioning.",
    "Deleterious": "Causing harm or damage.",
    "Demur": "To raise doubts or objections; to show reluctance.",
    "Denigrate": "To criticize unfairly; to belittle.",
    "Deride": "To express contempt for; to ridicule.",
    "Derivative": "Imitative of the work of another person; unoriginal.",
    "Desiccate": "To dry out thoroughly.",
    "Desultory": "Lacking a plan, purpose, or enthusiasm.",
    "Detrimental": "Tending to cause harm.",
    "Diatribe": "A forceful and bitter verbal attack.",
    "Didactic": "Intended to teach, particularly in having moral instruction.",
    "Diffident": "Modest or shy due to lack of self-confidence.",
    "Dilatory": "Slow to act; intended to cause delay.",
    "Dilettante": "A person who cultivates an area of interest without real commitment or knowledge.",
    "Dirge": "A lament for the dead, especially one forming part of a funeral rite.",
    "Disabuse": "To persuade someone that an idea or belief is mistaken.",
    "Discern": "To perceive or recognize something.",
    "Discomfit": "To make someone feel uneasy or embarrassed.",
    "Disparate": "Essentially different in kind; not allowing comparison.",
    "Dispassionate": "Not influenced by strong emotion; rational and impartial.",
    "Dissemble": "To conceal one's true motives, feelings, or beliefs.",
    "Disseminate": "To spread widely, especially information or ideas.",
    "Dissonance": "Lack of harmony among musical notes; a tension or clash from disharmonious elements.",
    "Distend": "To swell or cause to swell from pressure.",
    "Divest": "To strip or remove a title or position of authority.",
    "Dogmatic": "Inclined to lay down principles as incontrovertibly true.",
    "Doleful": "Expressing sorrow; mournful.",
    "Dour": "Relentlessly severe, stern, or gloomy in manner or appearance.",
    "Dupe": "To deceive or trick; a person who is easily deceived.",
    "Ebullient": "Cheerful and full of energy.",
    "Eccentric": "Unconventional and slightly strange.",
    "Eclectic": "Deriving ideas, style, or taste from a broad and diverse range of sources.",
    "Edify": "To instruct or improve someone morally or intellectually.",
    "Efface": "To erase from a surface; to make oneself appear insignificant.",
    "Effervescent": "Vivacious and enthusiastic.",
    "Efficacy": "The ability to produce a desired or intended result.",
    "Effrontery": "Insolent or impertinent behavior.",
    "Egalitarian": "Believing in the principle that all people are equal and deserve equal rights and opportunities.",
    "Egregious": "Outstandingly bad; shocking.",
    "Elucidate": "To make something clear; to explain.",
    "Emaciated": "Abnormally thin or weak, especially because of illness or lack of food.",
    "Embellish": "To make something more attractive by the addition of decorative details or features.",
    "Embroil": "To involve someone deeply in an argument, conflict, or difficult situation.",
    "Empirical": "Based on observation or experience rather than theory or pure logic.",
    "Enervate": "To weaken or drain of energy.",
    "Engender": "To cause or give rise to a feeling, situation, or condition.",
    "Enigma": "A person or thing that is mysterious, puzzling, or difficult to understand.",
    "Ennui": "A feeling of listlessness and dissatisfaction arising from a lack of occupation or excitement.",
    "Enumerate": "To mention one by one; to list.",
    "Ephemeral": "Lasting for a very short time.",
    "Epitome": "A perfect example of a particular quality or type.",
    "Equanimity": "Mental calmness, composure, and evenness of temper, especially in a difficult situation.",
    "Equivocate": "To use ambiguous language to conceal the truth or avoid committing oneself.",
    "Erudite": "Having or showing great knowledge or learning.",
    "Esoteric": "Intended for or likely to be understood by only a small number of people with specialized knowledge.",
    "Eulogy": "A speech or piece of writing that praises someone or something highly, typically someone who has just died.",
    "Euphemism": "A mild or indirect word substituted for one considered too harsh or blunt.",
    "Exacerbate": "To make a problem, bad situation, or negative feeling worse.",
    "Exculpate": "To show or declare that someone is not guilty of wrongdoing.",
    "Exigent": "Pressing; demanding.",
    "Exonerate": "To absolve someone from blame for a fault or wrongdoing.",
    "Expedite": "To make an action or process happen sooner or be accomplished more quickly.",
    "Explicit": "Stated clearly and in detail, leaving no room for confusion or doubt.",
    "Exposition": "A comprehensive description and explanation of an idea or theory.",
    "Extant": "Still in existence; surviving.",
    "Extraneous": "Irrelevant or unrelated to the subject being dealt with.",
    "Extrapolate": "To extend or infer something based on known data.",
    "Facetious": "Treating serious issues with deliberately inappropriate humor.",
        "Facetious": "Treating serious issues with deliberately inappropriate humor.",
    "Fallacious": "Based on a mistaken belief; logically unsound.",
    "Fastidious": "Very attentive to detail; hard to please.",
    "Fatuous": "Silly and pointless.",
    "Fawning": "Displaying exaggerated flattery or affection.",
    "Fecund": "Producing or capable of producing an abundance of offspring or new growth.",
    "Feeble": "Lacking physical strength or force.",
    "Fervid": "Intensely enthusiastic or passionate.",
    "Fetid": "Smelling extremely unpleasant.",
    "Fetter": "To restrain or restrict someone’s freedom.",
    "Flagrant": "Conspicuously offensive; blatant.",
    "Flout": "To openly disregard a rule or convention.",
    "Florid": "Excessively intricate or elaborate; having a red or flushed complexion.",
    "Fluctuate": "To rise and fall irregularly in number or amount.",
    "Foment": "To instigate or stir up trouble or rebellion.",
    "Forbear": "To refrain from doing something.",
    "Forestall": "To prevent or obstruct by taking action ahead of time.",
    "Foresight": "The ability to predict or the action of predicting what will happen.",
    "Fractious": "Irritable and quarrelsome.",
    "Frivolous": "Not having any serious purpose or value.",
    "Frugality": "The quality of being economical with money or resources.",
    "Furtive": "Attempting to avoid notice or attention, typically because of guilt or a belief that discovery would lead to trouble.",
    "Fusillade": "A series of shots fired or missiles thrown all at the same time or in quick succession.",
    "Futile": "Incapable of producing any useful result; pointless.",
    "Gainsay": "To deny or contradict a fact or statement.",
    "Garrulous": "Excessively talkative, especially on trivial matters.",
    "Gauche": "Lacking social grace; awkward or tactless.",
    "Gaudy": "Extravagantly bright or showy, typically so as to be tasteless.",
    "Genial": "Friendly and cheerful.",
    "Germane": "Relevant to a subject under consideration.",
    "Glib": "Fluent and voluble but insincere and shallow.",
    "Glutton": "An excessively greedy eater.",
    "Goad": "To provoke or annoy someone so as to stimulate action or reaction.",
    "Gregarious": "Fond of company; sociable.",
    "Grievous": "Causing sorrow or pain; serious or severe.",
    "Grovel": "To act in an obsequious manner in order to obtain someone's forgiveness or favor.",
    "Guile": "Sly or cunning intelligence.",
    "Gullible": "Easily persuaded to believe something; credulous.",
    "Hackneyed": "Lacking significance through having been overused; unoriginal and trite.",
    "Halcyon": "Denoting a period of time in the past that was idyllically happy and peaceful.",
    "Harangue": "A lengthy and aggressive speech.",
    "Harbinger": "A person or thing that announces or signals the approach of another.",
    "Haughty": "Arrogantly superior and disdainful.",
    "Hedonist": "A person who believes that the pursuit of pleasure is the most important goal of life.",
    "Heretical": "Holding an opinion at odds with what is generally accepted, especially in religion.",
    "Hermetic": "Sealed, airtight; insulated from outside influences.",
    "Heterodox": "Not conforming with accepted or orthodox standards or beliefs.",
    "Histrionic": "Overly theatrical or melodramatic in character or style.",
    "Homogeneous": "Of the same kind; alike.",
    "Hubris": "Excessive pride or self-confidence.",
    "Hyperbole": "Exaggerated statements or claims not meant to be taken literally.",
    "Hypocrite": "A person who pretends to have moral standards or beliefs to which their own behavior does not conform.",
        "Iconoclast": "A person who attacks cherished beliefs or institutions.",
    "Idiosyncrasy": "A mode of behavior or thought peculiar to an individual.",
    "Ignoble": "Not honorable in character or purpose.",
    "Ignominious": "Deserving or causing public disgrace or shame.",
    "Illicit": "Forbidden by law, rules, or custom.",
    "Imminent": "About to happen.",
    "Immutable": "Unchanging over time or unable to be changed.",
    "Impassive": "Not feeling or showing emotion.",
    "Impecunious": "Having little or no money.",
    "Impetuous": "Acting or done quickly without thought or care.",
    "Implacable": "Unable to be calmed down or satisfied.",
    "Implicit": "Implied though not plainly expressed.",
    "Impolitic": "Not showing good judgment; unwise.",
    "Importune": "To ask persistently and urgently.",
    "Imprecation": "A spoken curse.",
    "Impudent": "Not showing due respect for another person; impertinent.",
    "Inane": "Silly or stupid.",
    "Inchoate": "Just begun and so not fully formed or developed; rudimentary.",
    "Incisive": "Intelligently analytical and clear-thinking.",
    "Incongruous": "Not in harmony or keeping with the surroundings or other aspects of something.",
    "Incredulous": "Unwilling or unable to believe something.",
    "Indigent": "Poor; needy.",
    "Indolent": "Wanting to avoid activity or exertion; lazy.",
    "Ineffable": "Too great or extreme to be expressed in words.",
    "Inept": "Having or showing no skill; clumsy.",
    "Inexorable": "Impossible to stop or prevent.",
    "Ingenuous": "Innocent and unsuspecting.",
    "Inimical": "Tending to obstruct or harm; unfriendly or hostile.",
    "Iniquity": "Immoral or grossly unfair behavior.",
    "Innocuous": "Not harmful or offensive.",
    "Inscrutable": "Impossible to understand or interpret.",
    "Insipid": "Lacking flavor, vigor, or interest.",
    "Insular": "Ignorant of or uninterested in cultures, ideas, or peoples outside one's own experience.",
    "Intrepid": "Fearless; adventurous.",
    "Inundate": "To overwhelm or flood with things or people.",
    "Inure": "To accustom someone to something, especially something unpleasant.",
    "Invective": "Insulting, abusive, or highly critical language.",
    "Irascible": "Easily provoked to anger; very irritable.",
    "Irresolute": "Showing or feeling hesitancy; uncertain.",
    "Jargon": "Special words or expressions used by a profession or group that are difficult for others to understand.",
    "Jettison": "To throw or drop something from an aircraft or ship; to discard something unnecessary.",
    "Jocular": "Fond of or characterized by joking; humorous or playful.",
    "Jingoism": "Extreme patriotism, especially in the form of aggressive or warlike foreign policy.",
    "Jocund": "Cheerful and lighthearted.",
    "Judicious": "Having, showing, or done with good judgment or sense.",
    "Juxtapose": "To place two or more things side by side for comparison or contrast.",
    "Keen": "Having or showing eagerness or enthusiasm; sharp or penetrating.",
    "Kinetic": "Relating to or resulting from motion.",
    "Knavery": "Dishonest or unscrupulous behavior.",
    "Laconic": "Using very few words.",
    "Lament": "To mourn a loss or express sorrow.",
    "Languid": "Displaying or having a disinclination for physical exertion or effort; slow and relaxed.",
    "Largess": "Generosity in bestowing money or gifts.",
    "Latent": "Existing but not yet developed or manifest; hidden or concealed.",
    "Laudable": "Deserving praise and commendation.",
    "Lethargic": "Affected by lethargy; sluggish and apathetic.",
    "Libertine": "A person who behaves without moral principles or a sense of responsibility.",
    "Limpid": "Clear and transparent; easily understood.",
    "Loquacious": "Tending to talk a great deal; talkative.",
    "Lucid": "Expressed clearly; easy to understand.",
    "Lugubrious": "Looking or sounding sad and dismal.",
    "Magnanimous": "Generous or forgiving, especially toward a rival or less powerful person.",
    "Malevolent": "Having or showing a wish to do evil to others.",
    "Malleable": "Easily influenced or shaped.",
    "Maverick": "An independent-minded person.",
    "Mendacious": "Not telling the truth; lying.",
    "Mercurial": "Subject to sudden or unpredictable changes of mood or mind.",
    "Metamorphosis": "A complete change of form, structure, or substance.",
    "Meticulous": "Showing great attention to detail; very careful and precise.",
    "Milieu": "A person's social environment.",
    "Misanthrope": "A person who dislikes humankind and avoids human society.",
    "Mitigate": "To make less severe, serious, or painful.",
    "Modicum": "A small quantity of a particular thing.",
    "Morose": "Sullen and ill-tempered.",
    "Munificent": "Larger or more generous than is usual or necessary.",
    "Nadir": "The lowest point in the fortunes of a person or organization.",
    "Nascent": "Just coming into existence and beginning to display signs of future potential.",
    "Nebulous": "In the form of a cloud or haze; hazy; vague or ill-defined.",
    "Nefarious": "Wicked, villainous, or criminal.",
    "Negligible": "So small or unimportant as to be not worth considering.",
    "Neophyte": "A person who is new to a subject, skill, or belief.",
    "Nettle": "To irritate or annoy someone.",
    "Noisome": "Having an extremely offensive smell; disagreeable or unpleasant.",
    "Nonplussed": "Surprised and confused so much that one is unsure how to react.",
    "Noxious": "Harmful, poisonous, or very unpleasant.",
    "Nuance": "A subtle difference in or shade of meaning, expression, or sound.",
    "Obdurate": "Stubbornly refusing to change one's opinion or course of action.",
    "Obfuscate": "To deliberately make something unclear or difficult to understand.",
    "Obsequious": "Obedient or attentive to an excessive or servile degree.",
    "Obstinate": "Stubbornly refusing to change one's opinion despite attempts to persuade.",
    "Obviate": "To remove a need or difficulty; to prevent by taking precautionary measures.",
    "Occlude": "To stop, close up, or obstruct an opening or passage.",
    "Officious": "Assertive of authority in an annoyingly domineering way, especially with trivial matters.",
    "Onerous": "Involving a great deal of effort, difficulty, or responsibility.",
    "Opaque": "Not able to be seen through; not transparent; hard to understand.",
    "Opprobrium": "Harsh criticism or censure; public disgrace from shameful conduct.",
    "Ostensible": "Stated or appearing to be true, but not necessarily so.",
    "Ostentatious": "Characterized by vulgar or pretentious display; designed to impress or attract notice.",
    "Overwrought": "In a state of nervous excitement or anxiety; overelaborate or excessively complicated.",
    "Palliate": "To make a disease or its symptoms less severe without removing the cause.",
    "Palliative": "Relieving pain without dealing with the cause of the condition.",
    "Panegyric": "A public speech or published text in praise of someone or something.",
    "Paragon": "A person or thing regarded as a perfect example of a particular quality.",
    "Parsimony": "Extreme unwillingness to spend money or use resources.",
    "Partisan": "A strong supporter of a party, cause, or person.",
    "Paucity": "The presence of something in only small or insufficient quantities.",
    "Pedantic": "Excessively concerned with minor details or rules; overly academic.",
    "Penchant": "A strong or habitual liking for something or tendency to do something.",
    "Penitent": "Feeling or showing sorrow and regret for having done wrong; repentant.",
    "Perfidious": "Deceitful and untrustworthy.",
    "Perfunctory": "Carried out with minimum effort or reflection.",
    "Permeate": "To spread throughout something; to pervade.",
    "Perspicacious": "Having a ready insight into and understanding of things.",
    "Phlegmatic": "Having an unemotional and stolidly calm disposition.",
    "Pithy": "Concise and forcefully expressive.",
    "Placate": "To make someone less angry or hostile.",
    "Plastic": "Capable of being shaped or molded; adaptable or flexible.",
    "Platitude": "A remark or statement that has been used too often to be interesting or thoughtful.",
    "Plethora": "An excess of something.",
    "Polemic": "A strong verbal or written attack on someone or something.",
    "Pragmatic": "Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.",
    "Precarious": "Not securely held or in position; dangerously likely to fall or collapse.",
    "Precipitate": "To cause something to happen suddenly or unexpectedly.",
    "Precursor": "A person or thing that comes before another of the same kind.",
    "Predilection": "A preference or special liking for something.",
    "Prescient": "Having or showing knowledge of events before they take place.",
    "Prevaricate": "To speak or act in an evasive way.",
    "Probity": "The quality of having strong moral principles; honesty and decency.",
    "Proclivity": "A tendency to choose or do something regularly.",
    "Prodigal": "Spending money or resources freely and recklessly; wastefully extravagant.",
    "Profligate": "Recklessly extravagant or wasteful in the use of resources.",
    "Profound": "Very great or intense; having deep insight or understanding.",
    "Proliferate": "To increase rapidly in numbers; to multiply.",
    "Propitiate": "To win or regain the favor of someone by doing something that pleases them.",
    "Prosaic": "Lacking poetic beauty; dull or ordinary.",
    "Prudence": "The quality of being cautious and wise in practical matters.",
    "Quagmire": "A difficult, precarious, or entrapping position; a soft boggy area of land.",
    "Quell": "To suppress or put an end to; to subdue.",
    "Querulous": "Complaining in a petulant or whining manner.",
    "Quiescent": "In a state or period of inactivity or dormancy.",
    "Quintessential": "Representing the most perfect or typical example of a quality or class.",
    "Quixotic": "Exceedingly idealistic; unrealistic and impractical.",
    "Raconteur": "A person who tells anecdotes in a skillful and amusing way.",
    "Rarefied": "Distant from the lives and concerns of ordinary people; lofty.",
    "Raze": "To completely destroy a building, town, or other site.",
    "Rebuff": "To reject someone or something in an abrupt or ungracious manner.",
    "Recalcitrant": "Having an obstinately uncooperative attitude toward authority or discipline.",
    "Recant": "To say that one no longer holds an opinion or belief, especially one considered heretical.",
    "Recondite": "Little known; abstruse.",
    "Recrudescent": "Revival or reappearance, especially of something unpleasant.",
    "Redolent": "Strongly reminiscent or suggestive of something; fragrant or sweet-smelling.",
    "Refute": "To prove a statement or theory to be wrong or false.",
    "Relegate": "To assign to a lower position or less important role.",
    "Remonstrate": "To make a forcefully reproachful protest.",
    "Renege": "To go back on a promise, agreement, or commitment.",
    "Repartee": "Conversation or speech characterized by quick, witty comments or replies.",
    "Replete": "Filled or well-supplied with something.",
    "Reprehensible": "Deserving censure or condemnation.",
    "Reproach": "To express disapproval or disappointment.",
    "Reprobate": "An unprincipled person, often humorously or affectionately used.",
    "Repudiate": "To refuse to accept or be associated with.",
    "Rescind": "To revoke, cancel, or repeal a law, order, or agreement.",
    "Reticent": "Not revealing one's thoughts or feelings readily.",
    "Reverent": "Feeling or showing deep and solemn respect.",
    "Rhetoric": "The art of effective or persuasive speaking or writing.",
    "Ruminate": "To think deeply about something.",
    "Rustic": "Relating to the countryside; rural or simple in a charming way.",
    "Sacrosanct": "Regarded as too important or valuable to be interfered with.",
    "Sagacious": "Having or showing keen mental discernment and good judgment; wise.",
    "Salient": "Most noticeable or important.",
    "Salubrious": "Health-giving; healthy.",
    "Sanguine": "Optimistic or positive, especially in a bad or difficult situation.",
    "Sardonic": "Grimly mocking or cynical.",
    "Satiate": "To satisfy fully or to excess.",
    "Scintillating": "Brilliantly and excitingly clever or skillful.",
    "Scrupulous": "Diligent, thorough, and extremely attentive to details; very concerned to avoid doing wrong.",
    "Secular": "Not connected with religious or spiritual matters.",
    "Sedulous": "Showing dedication and diligence.",
    "Sedition": "Conduct or speech inciting people to rebel against authority.",
    "Serendipity": "The occurrence of events by chance in a happy or beneficial way.",
    "Servile": "Having or showing an excessive willingness to serve or please others.",
    "Simper": "To smile in an affectedly coy or ingratiating manner.",
    "Sinecure": "A position requiring little or no work but giving the holder status or financial benefit.",
    "Skeptic": "A person inclined to question or doubt accepted opinions.",
    "Skirt": "To go around or avoid dealing with something directly.",
    "Slander": "The action or crime of making a false spoken statement damaging to a person's reputation.",
    "Solicitous": "Characterized by or showing interest or concern.",
    "Soporific": "Tending to induce drowsiness or sleep.",
    "Specious": "Superficially plausible, but actually wrong.",
    "Spurious": "Not being what it purports to be; false or fake.",
    "Stentorian": "Loud and powerful in sound.",
    "Stigma": "A mark of disgrace associated with a particular circumstance, quality, or person.",
    "Stoic": "Enduring pain and hardship without showing one's feelings or complaining.",
    "Stolid": "Calm, dependable, and showing little emotion or animation.",
    "Striated": "Marked with striations or grooves.",
    "Stymie": "To prevent or hinder the progress of.",
    "Subpoena": "A writ ordering a person to attend a court.",
    "Substantiate": "To provide evidence to support or prove the truth of something.",
    "Subversive": "Seeking to undermine, overthrow, or destroy an established system or institution.",
    "Succinct": "Briefly and clearly expressed.",
    "Supercilious": "Behaving or looking as though one thinks they are superior to others.",
    "Superfluous": "Unnecessary, especially through being more than enough.",
    "Supplant": "To take the place of something or someone, often through force or strategy.",
    "Supplicate": "To ask or beg for something earnestly or humbly.",
    "Surfeit": "An excessive amount of something.",
    "Surreptitious": "Kept secret, especially because it would not be approved of.",
    "Sybarite": "A person who is self-indulgent in their fondness for luxury.",
    "Sycophant": "A person who acts obsequiously toward someone important in order to gain advantage.",
    "Synoptic": "Providing a general summary or overview.",
    "Tacit": "Understood or implied without being stated.",
    "Taciturn": "Reserved or uncommunicative in speech; saying little.",
    "Tangible": "Perceptible by touch; clear and definite.",
    "Tepid": "Showing little enthusiasm; lukewarm.",
    "Tirade": "A long, angry speech of criticism or accusation.",
    "Torpor": "A state of physical or mental inactivity; lethargy.",
    "Tractable": "Easy to control or influence.",
    "Transitory": "Not permanent; lasting for a short time.",
    "Trenchant": "Vigorous or incisive in expression or style.",
    "Trepidation": "A feeling of fear or agitation about something that may happen.",
    "Ubiquitous": "Present, appearing, or found everywhere.",
    "Umbrage": "Offense or annoyance.",
    "Unctuous": "Excessively flattering or insincerely earnest.",
    "Unequivocal": "Leaving no doubt; unambiguous.",
    "Untenable": "Not able to be maintained or defended against attack or objection.",
    "Upbraid": "To find fault with someone; to scold.",
    "Usurp": "To take a position of power illegally or by force.",
    "Vacillate": "To waver between different opinions or actions; to be indecisive.",
    "Vapid": "Offering nothing that is stimulating or challenging.",
    "Vehement": "Showing strong feeling; forceful, passionate, or intense.",
    "Venerate": "To regard with great respect; to revere.",
    "Veracity": "Conformity to facts; accuracy; truthfulness.",
    "Verbose": "Using more words than needed.",
    "Vestige": "A trace or remnant of something that is disappearing or no longer exists.",
    "Vex": "To make someone feel annoyed, frustrated, or worried.",
    "Vilify": "To speak or write about someone in an abusively disparaging manner.",
    "Vindicate": "To clear someone of blame or suspicion.",
    "Virtuoso": "A person highly skilled in a particular art, especially music.",
    "Viscous": "Having a thick, sticky consistency between solid and liquid.",
    "Vituperate": "To blame or insult someone in strong or violent language.",
    "Wane": "To decrease in size, extent, or degree.",
    "Wary": "Feeling or showing caution about possible dangers or problems.",
    "Welter": "A large number of items in no order; a confused mass.",
    "Whimsical": "Playfully quaint or fanciful, especially in an appealing and amusing way.",
    "Winsome": "Attractive or appealing in a fresh, innocent way.",
    "Wistful": "Having or showing a feeling of vague or regretful longing.",
    "Wry": "Using or expressing dry, especially mocking, humor.",
    "Xenophobia": "Dislike of or prejudice against people from other countries.",
    "Yawp": "To shout or exclaim hoarsely; to complain loudly.",
    "Yen": "A strong desire or craving.",
    "Yoke": "To join together; to harness or connect.",
    "Zeal": "Great energy or enthusiasm in pursuit of a cause or objective.",
    "Zealous": "Having or showing great energy or enthusiasm.",
    "Zenith": "The highest point reached by a celestial or other object; the peak.",
    "Zephyr": "A soft gentle breeze.",
    "Zest": "Great enthusiasm and energy."
}
